micronaut:
    application:
        name: encrypt-service
    server:
        port: -1
jackson:
    module-scan: false

---
consul:
    client:
        registration:
              enabled: true
        defaultZone: "${CONSUL_HOST:localhost}:${CONSUL_PORT:8500}"

---
tracing:
    zipkin:
        enabled: true
        http:
            url: http://localhost:9411
        sampler:
            probability: 1
