---
micronaut:
    application:
        name: gateway
jackson:
    module-scan: false
---
consul:
  client:
    registration:
      enabled: true
    defaultZone: "${CONSUL_HOST:localhost}:${CONSUL_PORT:8500}"
